"""
models/schemas.py
-----------------
Pydantic data models for CallSense-AI.

These models define the data contracts shared across all agents,
services, and the UI. Pydantic v2 enforces type validation and
serialisation automatically at every boundary.
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class ProcessingStatus(str, Enum):
    """Lifecycle status of a call as it moves through the pipeline."""

    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class CallMetadata(BaseModel):
    """Stores information about the uploaded audio file."""

    file_name: str = Field(..., description="Original name of the uploaded audio file")
    file_type: str = Field(..., description="MIME type or extension, e.g. 'audio/mp3'")
    file_size_bytes: int = Field(..., ge=0, description="File size in bytes")
    duration_seconds: float = Field(..., ge=0.0, description="Audio duration in seconds")
    language: Optional[str] = Field(None, description="Detected or provided BCP-47 language tag")
    uploaded_at: datetime = Field(default_factory=datetime.utcnow, description="UTC timestamp of upload")


class CallSummary(BaseModel):
    """Stores the structured summary generated by the Summarization Agent."""

    summary: str = Field(..., description="One-sentence overview of the call")
    customer_issue: str = Field(..., description="Main issue raised by the customer")
    resolution: str = Field(..., description="How the issue was resolved")
    action_items: List[str] = Field(default_factory=list, description="Follow-up tasks identified")
    customer_sentiment: str = Field(..., description="Overall customer sentiment, e.g. 'positive'")
    key_topics: List[str] = Field(default_factory=list, description="Main topics discussed")


class QualityScore(BaseModel):
    """Stores QA evaluation generated by the Quality Score Agent."""

    empathy_score: float = Field(..., ge=0.0, le=10.0, description="Empathy score out of 10")
    professionalism_score: float = Field(..., ge=0.0, le=10.0, description="Professionalism score out of 10")
    resolution_score: float = Field(..., ge=0.0, le=10.0, description="Resolution effectiveness score out of 10")
    compliance_score: float = Field(..., ge=0.0, le=10.0, description="Compliance adherence score out of 10")
    overall_score: float = Field(..., ge=0.0, le=10.0, description="Composite score out of 10")
    feedback: str = Field(..., description="Narrative feedback for the human agent")


class RoutingDecision(BaseModel):
    """Stores the routing decision generated by the Routing Agent."""

    status: str = Field(..., description="Routing outcome, e.g. 'resolved', 'escalated'")
    next_agent: str = Field(..., description="Team or agent the call is routed to")
    reason: str = Field(..., description="Explanation for the routing decision")
    retry_count: int = Field(default=0, ge=0, description="Number of times routing was retried")
